# Generated by Django 5.0.6 on 2024-10-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibitionartworks',
            old_name='artwork',
            new_name='artwork_id',
        ),
        migrations.RenameField(
            model_name='exhibitionartworks',
            old_name='exhibition',
            new_name='exhibition_id',
        ),
    ]
