# Generated by Django 5.0.6 on 2024-10-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='artist',
            new_name='artist_id',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='multimedia',
            old_name='artwork',
            new_name='artwork_id',
        ),
    ]
